language: cpp
compiler:
    - gcc
    - clang
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
            - clang-3.4
before_script:
    - if [ $CXX = g++ ]; then export CXX=g++-4.8; fi
    - if [ $CXX = clang++ ]; then export CXX=clang++-3.4; fi
script: cd tests && cmake . && make check
branches:
    only: master
os:
    - linux
    - osx
