language: cpp
compiler:
    - gcc
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
before_script:
    - if [ $CXX = g++ ]; then export CXX=g++-4.8; fi
script: cd tests && cmake . && make check
branches:
    only: master
os:
    - linux
    - osx
